### ISSUE TITLE
服务器返回错误的数据，会崩溃！

### ISSUE THREAD

**Issue by Biswangluo** [pengjianbo/OkHttpFinal#19]
java.nio.charset.IllegalCharsetNameException: 'utf-8'
                                                              at java.nio.charset.Charset.checkCharsetName(Charset.java:197)
                                                              at java.nio.charset.Charset.forName(Charset.java:295)
                                                              at okhttp3.MediaType.charset(MediaType.java:103)
                                                              at okhttp3.ResponseBody.charset(ResponseBody.java:114)
                                                              at okhttp3.ResponseBody.string(ResponseBody.java:109)
                                                              at cn.finalteam.okhttpfinal.OkHttpTask.handlerResponse(OkHttpTask.java:180)
                                                              at cn.finalteam.okhttpfinal.OkHttpTask.onResponse(OkHttpTask.java:168)
                                                              at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                              at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:818)
-

**Comment by Biswangluo** [comment]
如果请求正常，服务器返回了正确的JSON，一切正常，如果请求不正常，服务器返回了一大堆乱七八糟的数据 就会挂掉。
